# Generated by Django 5.1.7 on 2025-03-22 12:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auction_closingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='creationDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
