# Generated by Django 5.1.7 on 2025-03-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='id_auction',
            new_name='auction',
        ),
    ]
